# Generated by Django 3.0.5 on 2020-05-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200515_1849'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodesk',
            name='photo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Photo'),
        ),
        migrations.AddField(
            model_name='photouser',
            name='photo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owners_photo', related_query_name='owners_photo', to='blog.Photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='users', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='photouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', related_query_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
