# Generated by Django 3.0.5 on 2020-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200515_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=0, upload_to='users/%Y/%m/%d/'),
        ),
    ]
