# Generated by Django 3.0.5 on 2020-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200521_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
