# Generated by Django 3.0.5 on 2020-05-21 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_dislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', through='blog.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
