# Generated by Django 3.0.5 on 2020-05-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_photo_users_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
